/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: f2bedd522e34e660f4f87e36688d6183)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	DEPLOYMENT_PROVIDER?: "cloudflare";
	DEPLOYMENT_ENVIRONMENT?: "canary";
	PLATPHORM_CANARY?: "true";
	NEXT_PUBLIC_APP_URL?: "https://json.innovativefuturesolutions.com";
	NEXT_PUBLIC_CANONICAL_URL?: "https://json.platphormnews.com";
	PLATPHORM_TRACE_BASE_URL?: "https://trace.platphormnews.com";
	PLATPHORM_REQUIRE_API_KEY?: "false";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./cloudflare/worker");
	}
	interface CustomDomainEnv {
		ASSETS: Fetcher;
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEPLOYMENT_PROVIDER" | "DEPLOYMENT_ENVIRONMENT" | "PLATPHORM_CANARY" | "NEXT_PUBLIC_APP_URL" | "NEXT_PUBLIC_CANONICAL_URL" | "PLATPHORM_TRACE_BASE_URL" | "PLATPHORM_REQUIRE_API_KEY">> {}
}
